/**
 * Verifies counter sales — `npm run db:pos-check`.
 *
 * The property that matters: a sale, its stock decrement and its movement rows
 * are one atomic unit. A sale that took stock without recording it — or a
 * recorded sale that never moved stock — is worse than a failed sale, because
 * nothing downstream can detect it.
 *
 * Self-cleaning: every order it creates is deleted and stock restored.
 */
import "dotenv/config";
import { Client } from "pg";

const TAG = "pos-check:";
let pass = 0, fail = 0;
const ok = (l: string, c: boolean, d = "") => {
  if (c) { pass++; console.log(`  \x1b[32mPASS\x1b[0m ${l} ${d}`); }
  else { fail++; console.log(`  \x1b[31mFAIL\x1b[0m ${l} ${d}`); }
};

async function main() {
  const c = new Client({ connectionString: process.env.DIRECT_URL });
  await c.connect();

  const admin = (await c.query(`select id from admin_users limit 1`)).rows[0];
  const picks = (await c.query(`
    select si.id, si.stock, si.effective_price::text price, si.store_id,
           ps.id size_id, ps.label, p.id product_id, p.name
      from store_inventory si
      join product_sizes ps on ps.id = si.product_size_id
      join products p on p.id = ps.product_id
     where si.is_active and si.stock >= 5
     limit 2`)).rows;

  const startUnits = (await c.query(`select coalesce(sum(stock),0)::int n from store_inventory`)).rows[0].n;
  const madeOrders: string[] = [];

  /** Mirrors createSaleAction: order + items + decrement + movements, atomically. */
  async function sell(lines: { row: (typeof picks)[number]; qty: number }[], key: string) {
    const total = lines.reduce((a, l) => a + Number(l.row.price) * l.qty, 0);
    const vat = Math.round((total * 12) / 112 * 100) / 100;
    await c.query("begin");
    try {
      const o = await c.query(
        `insert into orders (idempotency_key, order_code, store_id, status, payment_status,
            fulfillment_type, customer_name, customer_phone, customer_notes,
            subtotal, delivery_fee, discount_total, vat_amount, payment_verified_at,
            payment_verified_by, completed_at)
         values ($1,'',$2,'completed','verified','pickup','Walk-in customer',null,
                 'Counter sale probe',$3,0,0,$4,now(),$5,now())
         returning id, order_code`,
        [TAG + key, lines[0].row.store_id, total.toFixed(2), vat.toFixed(2), admin.id]
      );
      const orderId = o.rows[0].id;
      for (const l of lines) {
        await c.query(
          `insert into order_items (order_id, store_inventory_id, product_id, product_size_id,
              product_name, size_label, unit_price, quantity)
           values ($1,$2,$3,$4,$5,$6,$7,$8)`,
          [orderId, l.row.id, l.row.product_id, l.row.size_id, l.row.name, l.row.label, l.row.price, l.qty]
        );
        const dec = await c.query(
          `update store_inventory set stock = stock - $2 where id=$1 and stock >= $2 returning stock`,
          [l.row.id, l.qty]
        );
        if (dec.rowCount === 0) throw new Error("SOLD_OUT");
        await c.query(
          `insert into inventory_movements (store_inventory_id, delta, balance_after, reason, order_id, actor_id)
           values ($1,$2,$3,'counter_sale',$4,$5)`,
          [l.row.id, -l.qty, dec.rows[0].stock, orderId, admin.id]
        );
      }
      await c.query("commit");
      madeOrders.push(orderId);
      return { orderId, code: o.rows[0].order_code, total };
    } catch (e) {
      await c.query("rollback");
      throw e;
    }
  }

  try {
    console.log("\n1. A counter sale writes one coherent record");
    const before = picks.map((p) => p.stock);
    const sale = await sell([{ row: picks[0], qty: 2 }, { row: picks[1], qty: 1 }], "1");
    ok("order code generated by the trigger", /^AT-[0-9A-Z]{6}$/.test(sale.code), sale.code);

    const row = (await c.query(
      `select status::text st, payment_status::text ps, fulfillment_type::text ft,
              customer_phone, total_amount::text total from orders where id=$1`, [sale.orderId]
    )).rows[0];
    ok("completed on the spot", row.st === "completed");
    ok("paid on the spot", row.ps === "verified");
    ok("recorded as pickup", row.ft === "pickup");
    ok("walk-in has no phone (constraint now allows null)", row.customer_phone === null);
    ok("total matches the basket", Number(row.total) === Math.round(sale.total * 100) / 100,
      `${row.total} vs ${sale.total.toFixed(2)}`);

    console.log("\n2. Stock moved, and the movement explains it");
    const after = (await c.query(
      `select id, stock from store_inventory where id = any($1::uuid[]) order by id`,
      [picks.map((p) => p.id)]
    )).rows;
    const byId = new Map(after.map((r) => [r.id, r.stock]));
    ok("first line decremented by 2", byId.get(picks[0].id) === before[0] - 2,
      `${before[0]} → ${byId.get(picks[0].id)}`);
    ok("second line decremented by 1", byId.get(picks[1].id) === before[1] - 1,
      `${before[1]} → ${byId.get(picks[1].id)}`);

    const moves = (await c.query(
      `select delta, balance_after, reason, actor_id from inventory_movements where order_id=$1 order by id`,
      [sale.orderId]
    )).rows;
    ok("one movement per line", moves.length === 2, `${moves.length}`);
    ok("deltas are negative", moves.every((m) => m.delta < 0));
    ok("balance_after matches live stock",
      moves.every((m, i) => m.balance_after === byId.get(picks[i].id)));
    ok("reason is counter_sale", moves.every((m) => m.reason === "counter_sale"));
    ok("cashier recorded", moves.every((m) => m.actor_id === admin.id));

    console.log("\n3. Overselling is impossible");
    const live = (await c.query(`select stock from store_inventory where id=$1`, [picks[0].id])).rows[0].stock;
    let blocked = false;
    try {
      await sell([{ row: { ...picks[0] }, qty: live + 1 }], "oversell");
    } catch { blocked = true; }
    ok("a sale beyond stock is refused", blocked);
    const afterFail = (await c.query(`select stock from store_inventory where id=$1`, [picks[0].id])).rows[0].stock;
    ok("failed sale left stock untouched", afterFail === live, `${afterFail}`);
    const orphan = (await c.query(
      `select count(*)::int n from orders where idempotency_key = $1`, [TAG + "oversell"]
    )).rows[0].n;
    ok("failed sale left no order behind", orphan === 0);

    console.log("\n4. It reaches the rest of the system");
    const inOrders = (await c.query(
      `select count(*)::int n from orders where id=$1 and status <> 'cancelled'`, [sale.orderId]
    )).rows[0].n;
    ok("appears in the orders list", inOrders === 1);
    const inRevenue = (await c.query(
      `select count(*)::int n from orders
        where id=$1 and payment_status='verified' and status <> 'cancelled'`, [sale.orderId]
    )).rows[0].n;
    ok("counts toward dashboard revenue", inRevenue === 1);
    const invoiceable = (await c.query(
      `select count(*)::int n from orders where id=$1 and status <> 'cancelled'`, [sale.orderId]
    )).rows[0].n;
    ok("invoiceable", invoiceable === 1);
  } finally {
    for (const id of madeOrders) {
      await c.query(
        `update store_inventory si set stock = si.stock + oi.quantity
           from order_items oi where oi.order_id=$1 and oi.store_inventory_id=si.id`,
        [id]
      );
      await c.query(`delete from inventory_movements where order_id=$1`, [id]);
    }
    await c.query(`delete from orders where idempotency_key like $1`, [TAG + "%"]);
    const units = (await c.query(`select coalesce(sum(stock),0)::int n from store_inventory`)).rows[0].n;
    const moves = (await c.query(`select count(*)::int n from inventory_movements`)).rows[0].n;
    console.log(`\n  cleanup: ${madeOrders.length} sale(s) reversed`);
    console.log(`  inventory_units ${units} (expected ${startUnits}) · movements ${moves}`);
    if (units !== startUnits) { fail++; console.log("  \x1b[31mFAIL\x1b[0m stock not restored"); }
    await c.end();
  }

  console.log(`\n${fail === 0 ? "\x1b[32m" : "\x1b[31m"}${pass} passed, ${fail} failed\x1b[0m\n`);
  process.exitCode = fail === 0 ? 0 : 1;
}

main().catch((e) => {
  console.error("\ncheck failed:", e instanceof Error ? e.message : e);
  process.exitCode = 1;
});
