/**
 * Demo order seed — `npm run db:seed-demo`
 *
 * Generates ~200 orders across the last 12 months so the dashboard has
 * something real to aggregate. Every row is tagged `idempotency_key =
 * 'demo-seed:<n>'`, which is what `npm run db:purge-demo` deletes.
 *
 * Why the tag isn't on order_code: that column is constrained to
 * ^AT-[0-9A-Z]{6}$ and is generated by the prepare_order() BEFORE trigger.
 *
 * This never touches store_inventory. Nothing deducts stock on order_items
 * insert, and restore_stock_on_cancel only fires on an UPDATE of status —
 * cancelled orders here are inserted already-cancelled.
 */
import "dotenv/config";
import { Client } from "pg";

const TARGET_ORDERS = 200;
const TAG = "demo-seed:";

/** Deterministic RNG so repeated runs produce the same shape. */
function makeRng(seed: number) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 0x100000000;
  };
}
const rnd = makeRng(20260823);
const pick = <T,>(xs: T[]): T => xs[Math.floor(rnd() * xs.length)];
const between = (a: number, b: number) => a + Math.floor(rnd() * (b - a + 1));

const FIRST = ["Maria", "Jose", "Ana", "Juan", "Rosa", "Pedro", "Liza", "Mark", "Grace", "Nico", "Bea", "Ramon"];
const LAST = ["Santos", "Reyes", "Cruz", "Bautista", "Garcia", "Mendoza", "Torres", "Flores", "Ramos", "Aquino"];
const BARANGAY = ["San Isidro", "Kalayaan", "Mahabang Parang", "Pantok", "Layunan", "Tatala", "Bilibiran"];
const CITY = ["Angono", "Binangonan", "Taytay", "Cardona"];

type Inv = {
  inv_id: string;
  size_id: string;
  product_id: string;
  product_name: string;
  size_label: string;
  price: string;
};

/**
 * Status combinations, weighted. Revenue on the dashboard counts
 * payment_status='verified' AND status<>'cancelled', so this mix deliberately
 * includes rows that must NOT show up as revenue.
 */
const OUTCOMES: Array<{ w: number; status: string; payment: string }> = [
  { w: 62, status: "completed", payment: "verified" },
  { w: 8, status: "ready", payment: "verified" },
  { w: 6, status: "out_for_delivery", payment: "verified" },
  { w: 6, status: "preparing", payment: "verified" },
  { w: 5, status: "confirmed", payment: "awaiting_verification" },
  { w: 5, status: "pending", payment: "unpaid" },
  { w: 8, status: "cancelled", payment: "unpaid" },
];
const OUTCOME_TOTAL = OUTCOMES.reduce((a, o) => a + o.w, 0);
function rollOutcome() {
  let r = rnd() * OUTCOME_TOTAL;
  for (const o of OUTCOMES) {
    if ((r -= o.w) <= 0) return o;
  }
  return OUTCOMES[0];
}

/** Recent weeks are busier than a year ago — a flat distribution looks fake. */
function rollCreatedAt(): Date {
  const now = Date.now();
  const skew = Math.pow(rnd(), 1.7); // bias toward 0 == recent
  const daysAgo = skew * 365;
  const d = new Date(now - daysAgo * 86_400_000);
  // Shop hours in Manila (UTC+8): 08:00–19:00 local -> 00:00–11:00 UTC.
  d.setUTCHours(between(0, 11), between(0, 59), between(0, 59), 0);
  return d;
}

const money = (n: number) => n.toFixed(2);

async function main() {
  const c = new Client({ connectionString: process.env.DIRECT_URL });
  await c.connect();

  try {
    const existing = await c.query(
      `select count(*)::int n from orders where idempotency_key like $1`,
      [TAG + "%"]
    );
    if (existing.rows[0].n > 0) {
      console.log(
        `${existing.rows[0].n} demo orders already exist. Run \`npm run db:purge-demo\` first.`
      );
      return;
    }

    const stores = (
      await c.query(`select id, name, delivery_fee::text from stores where is_active order by display_order`)
    ).rows as Array<{ id: string; name: string; delivery_fee: string }>;

    const methods = (
      await c.query(`select id, name, type::text from payment_methods where is_active`)
    ).rows as Array<{ id: string; name: string; type: string }>;

    // Real inventory joined to real sizes, so prices and names are genuine.
    const invByStore = new Map<string, Inv[]>();
    for (const s of stores) {
      const rows = (
        await c.query(
          `select si.id inv_id, ps.id size_id, p.id product_id, p.name product_name,
                  ps.label size_label, si.effective_price::text price
             from store_inventory si
             join product_sizes ps on ps.id = si.product_size_id
             join products p on p.id = ps.product_id
            where si.store_id = $1 and si.is_active and ps.is_active and p.is_active`,
          [s.id]
        )
      ).rows as Inv[];
      invByStore.set(s.id, rows);
    }
    console.log(
      `reference data: ${stores.length} stores, ${methods.length} payment methods, ` +
        `${[...invByStore.values()].reduce((a, r) => a + r.length, 0)} inventory rows`
    );

    // Unequal store volume so the "sales by location" chart has something to say.
    const storeWeights = [0.45, 0.33, 0.22];

    await c.query("begin");

    let itemCount = 0;
    for (let n = 0; n < TARGET_ORDERS; n++) {
      const roll = rnd();
      const storeIdx = roll < storeWeights[0] ? 0 : roll < storeWeights[0] + storeWeights[1] ? 1 : 2;
      const store = stores[Math.min(storeIdx, stores.length - 1)];
      const pool = invByStore.get(store.id)!;
      if (!pool.length) continue;

      const createdAt = rollCreatedAt();
      const rolled = rollOutcome();
      const fulfillment = rnd() < 0.6 ? "delivery" : "pickup";

      // Status and fulfilment are rolled independently, which can produce a
      // combination the shop could never reach — a pickup order that is "out
      // for delivery", or a delivery order sitting on the pickup-only "ready".
      // Left alone these are not just cosmetic: they fall off the state machine
      // and the order can never be advanced again.
      const status =
        fulfillment === "pickup" && rolled.status === "out_for_delivery"
          ? "ready"
          : fulfillment === "delivery" && rolled.status === "ready"
            ? "out_for_delivery"
            : rolled.status;
      const outcome = { ...rolled, status };

      // 1–4 distinct lines.
      const lines: Array<{ inv: Inv; qty: number }> = [];
      const seen = new Set<string>();
      for (let i = 0, want = between(1, 4); i < want; i++) {
        const inv = pick(pool);
        if (seen.has(inv.inv_id)) continue;
        seen.add(inv.inv_id);
        lines.push({ inv, qty: between(1, 3) });
      }

      const subtotal = lines.reduce((a, l) => a + Number(l.inv.price) * l.qty, 0);
      // pickup_has_no_fee: pickup must have delivery_fee = 0.
      const deliveryFee = fulfillment === "delivery" ? Number(store.delivery_fee) : 0;
      // discount_not_over_subtotal
      const discount = rnd() < 0.15 ? Math.min(Math.round(subtotal * 0.1), Math.floor(subtotal)) : 0;
      const total = subtotal + deliveryFee - discount;
      // VAT-inclusive pricing: the 12% is already inside the total.
      const vat = Math.round((total * 12) / 112 * 100) / 100;

      const name = `${pick(FIRST)} ${pick(LAST)}`;
      const method = pick(methods);
      const isDelivery = fulfillment === "delivery";

      const confirmedAt =
        outcome.status === "pending" ? null : new Date(createdAt.getTime() + 20 * 60_000);
      const completedAt =
        outcome.status === "completed" ? new Date(createdAt.getTime() + 26 * 3600_000) : null;
      const cancelledAt =
        outcome.status === "cancelled" ? new Date(createdAt.getTime() + 90 * 60_000) : null;

      // total_amount is intentionally NOT set — prepare_order() computes it,
      // and totals_balance rejects the row if our arithmetic disagreed.
      const res = await c.query(
        `insert into orders (
            idempotency_key, store_id, status, payment_status, fulfillment_type,
            customer_name, customer_phone, customer_email,
            address_line, barangay, city, province,
            subtotal, delivery_fee, discount_total, vat_amount, is_vat_inclusive,
            payment_method_id, payment_method_name,
            payment_verified_at, confirmed_at, completed_at, cancelled_at, cancel_reason,
            created_at, updated_at
         ) values (
            $1,$2,$3::order_status,$4::payment_status,$5::fulfillment_type,
            $6,$7,$8,
            $9,$10,$11,$12,
            $13,$14,$15,$16,true,
            $17,$18,
            $19,$20,$21,$22,$23,
            $24,$24
         ) returning id`,
        [
          `${TAG}${n}`,
          store.id,
          outcome.status,
          outcome.payment,
          fulfillment,
          name,
          `09${between(100000000, 999999999)}`,
          rnd() < 0.7 ? `${name.toLowerCase().replace(/[^a-z]/g, ".")}@example.com` : null,
          // delivery_needs_address: delivery must carry an address_line.
          isDelivery ? `${between(1, 240)} ${pick(BARANGAY)} St.` : null,
          isDelivery ? pick(BARANGAY) : null,
          isDelivery ? pick(CITY) : null,
          "Rizal",
          money(subtotal),
          money(deliveryFee),
          money(discount),
          money(vat),
          method.id,
          method.name,
          outcome.payment === "verified" ? new Date(createdAt.getTime() + 45 * 60_000) : null,
          confirmedAt,
          completedAt,
          cancelledAt,
          outcome.status === "cancelled" ? "Customer changed their mind" : null,
          createdAt,
        ]
      );

      const orderId = res.rows[0].id as string;

      for (const l of lines) {
        await c.query(
          `insert into order_items (
              order_id, store_inventory_id, product_id, product_size_id,
              product_name, size_label, unit_price, quantity, created_at
           ) values ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,
          [
            orderId,
            l.inv.inv_id,
            l.inv.product_id,
            l.inv.size_id,
            l.inv.product_name,
            l.inv.size_label,
            l.inv.price,
            l.qty,
            createdAt,
          ]
        );
        itemCount++;
      }
    }

    await c.query("commit");
    console.log(`\nseeded ${TARGET_ORDERS} orders / ${itemCount} line items.`);
  } catch (e) {
    await c.query("rollback").catch(() => {});
    throw e;
  }

  const summary = await c.query(`
    select
      (select count(*) from orders where idempotency_key like '${TAG}%')::int demo_orders,
      (select count(*) from order_items)::int items,
      (select count(*) from order_status_history)::int history,
      (select coalesce(sum(stock),0) from store_inventory)::int inventory_units
  `);
  console.table(summary.rows);
  // No hardcoded figure: it goes stale the moment stock legitimately changes.
  // The seed inserts orders that have NOT deducted (stock_deducted_at is null),
  // so this number must equal whatever it was before the seed ran.
  console.log("inventory_units above must match its value before seeding — the seed never moves stock.\n");
  await c.end();
}

main().catch((e) => {
  console.error("\nseed failed:", e instanceof Error ? e.message : e);
  process.exitCode = 1;
});
